import { AkanContextAnalyzer, Prompter, runner, type Workspace } from "@akanjs/devkit";

type AgentTarget = "cursor" | "agents-md" | "claude";

const targetPaths: Record<AgentTarget, string> = {
  cursor: ".cursor/rules/akan.mdc",
  "agents-md": "AGENTS.md",
  claude: "CLAUDE.md",
};

const targetTitle: Record<AgentTarget, string> = {
  cursor: "Akan Cursor Rules",
  "agents-md": "Akan Agent Rules",
  claude: "Akan Claude Rules",
};

const renderAgentRules = async (workspace: Workspace, target: AgentTarget) => {
  const context = await AkanContextAnalyzer.analyze(workspace);
  const frameworkGuide = await Prompter.getInstruction("framework");
  return `# ${targetTitle[target]}

This file is generated by \`akan agent install ${target}\`.

## Workspace

- Repo: ${context.repoName}
- Apps: ${context.apps.map((app) => app.name).join(", ") || "none"}
- Libraries: ${context.libs.map((lib) => lib.name).join(", ") || "none"}
- Packages: ${context.pkgs.map((pkg) => pkg.name).join(", ") || "none"}

## Akan Module Abstracts

- Before changing a domain, service, or scalar module, read its \`*.abstract.md\` file first.
- Update the abstract when business invariants, workflows, or public behavior change.
- Do not update the abstract for formatting-only, import-only, or style-only changes.
- Service modules live in \`lib/_<service>\`, but their abstract file is \`<service>.abstract.md\`.

## Generated Files

Do not hand-edit generated Akan files such as ${context.generatedFiles.map((file) => `\`${file}\``).join(", ")}.
If generated output is stale or broken, update the owning source file and run \`akan repair generated\` or \`akan sync <app-or-lib>\`.

## MCP Workflow Policy

- Prefer Akan MCP workflows before direct source edits.
- Direct source edits are denied when an allowlisted Akan workflow or repair tool can perform the change.
- Use \`akan mcp --mode plan\` to inspect \`list_workflows\`, \`explain_workflow\`, and \`plan_workflow\`.
- If \`plan_workflow\` returns \`planPath\` or \`next.tool=apply_workflow\`, call \`apply_workflow({ planPath })\` before editing source files directly.
- Use \`akan mcp --mode apply\` only for allowlisted \`apply_workflow\`, \`run_validation\`, and repair tools.
- After \`apply_workflow\`, run \`run_validation\` with \`validationTarget\` when present; otherwise use \`applyReportPath\`.
- If no workflow exists, or apply reports unsupported/no-op/failed diagnostics that require manual action, keep edits scoped to owning source files and never patch generated files directly.
- For compound requests, split the request into workflows and apply each \`planPath\` in order, such as \`create-module\` followed by \`add-field\`.

## Validation

${context.validationCommands.map((command) => `- \`${command}\``).join("\n")}

## Framework Guide

${frameworkGuide.trim()}
`;
};

export class AgentRunner extends runner("agent") {
  async install(workspace: Workspace, targets: AgentTarget[], { force = false }: { force?: boolean } = {}) {
    const written: string[] = [];
    for (const target of targets) {
      const filePath = targetPaths[target];
      if (!force && (await workspace.exists(filePath))) {
        throw new Error(`${filePath} already exists. Re-run with --force to overwrite it.`);
      }
      const content = await renderAgentRules(workspace, target);
      await workspace.writeFile(filePath, content, { overwrite: force });
      written.push(filePath);
    }
    return written;
  }
}
