import { AkanContextAnalyzer, Prompter, runner, type Workspace } from "@akanjs/devkit";

type AgentTarget = "cursor" | "agents-md" | "claude";

const targetPaths: Record<AgentTarget, string> = {
  cursor: ".cursor/rules/akan.mdc",
  "agents-md": "AGENTS.md",
  claude: "CLAUDE.md",
};

const AGENT_BLOCK_START = "<!-- akan:agent:start -->";
const AGENT_BLOCK_END = "<!-- akan:agent:end -->";

// The generated, workspace-derived section. It is the only part of AGENTS.md that
// `akan agent install` rewrites; everything outside the markers is preserved.
const renderManagedBlock = async (workspace: Workspace) => {
  const context = await AkanContextAnalyzer.analyze(workspace);
  const frameworkGuide = await Prompter.getInstruction("framework");
  return `## Workspace

- Repo: ${context.repoName}
- Apps: ${context.apps.map((app) => app.name).join(", ") || "none"}
- Libraries: ${context.libs.map((lib) => lib.name).join(", ") || "none"}
- Packages: ${context.pkgs.map((pkg) => pkg.name).join(", ") || "none"}

## Akan Module Abstracts

- Before changing a domain, service, or scalar module, read its \`*.abstract.md\` file first.
- Update the abstract when business invariants, workflows, or public behavior change.
- Do not update the abstract for formatting-only, import-only, or style-only changes.
- Service modules live in \`lib/_<service>\`, but their abstract file is \`<service>.abstract.md\`.

## Generated Files

Do not hand-edit generated Akan files such as ${context.generatedFiles.map((file) => `\`${file}\``).join(", ")}.
If generated output is stale or broken, update the owning source file and run \`akan repair generated\` or \`akan sync <app-or-lib>\`.

## MCP Workflow Policy

- Prefer Akan MCP workflows before direct source edits.
- Direct source edits are denied when an allowlisted Akan workflow or repair tool can perform the change.
- Use \`akan mcp --mode plan\` to inspect \`list_workflows\`, \`explain_workflow\`, and \`plan_workflow\`.
- If \`plan_workflow\` returns \`planPath\` or \`next.tool=apply_workflow\`, call \`apply_workflow({ planPath })\` before editing source files directly.
- Use \`akan mcp --mode apply\` only for allowlisted \`apply_workflow\`, \`run_validation\`, and repair tools.
- After \`apply_workflow\`, run \`run_validation\` with \`validationTarget\` when present; otherwise use \`applyReportPath\`.
- If no workflow exists, or apply reports unsupported/no-op/failed diagnostics that require manual action, keep edits scoped to owning source files and never patch generated files directly.
- For compound requests, split the request into workflows and apply each \`planPath\` in order, such as \`create-module\` followed by \`add-field\`.

## Validation

${context.validationCommands.map((command) => `- \`${command}\``).join("\n")}

## Framework Guide

${frameworkGuide.trim()}`;
};

// Replace the content between the akan:agent markers, preserving everything else.
// When the markers are absent (a hand-written or freshly scaffolded AGENTS.md), append them.
const upsertManagedBlock = (existing: string, block: string) => {
  const managed = `${AGENT_BLOCK_START}\n${block}\n${AGENT_BLOCK_END}`;
  const startIndex = existing.indexOf(AGENT_BLOCK_START);
  const endIndex = existing.indexOf(AGENT_BLOCK_END);
  if (startIndex >= 0 && endIndex > startIndex) {
    return `${existing.slice(0, startIndex)}${managed}${existing.slice(endIndex + AGENT_BLOCK_END.length)}`;
  }
  return `${existing.replace(/\s*$/, "")}\n\n${managed}\n`;
};

const renderAgentsMd = async (workspace: Workspace, existing: string | null) => {
  const block = await renderManagedBlock(workspace);
  if (existing?.trim()) return upsertManagedBlock(existing, block);
  const context = await AkanContextAnalyzer.analyze(workspace);
  return `# ${context.repoName} Agent Guide

This file is the single source of truth for coding agents in this workspace. Claude Code reads it through
\`CLAUDE.md\` (\`@AGENTS.md\`) and Cursor through \`.cursor/rules/akan.mdc\`. The section between the
\`akan:agent\` markers is regenerated by \`akan agent install\`; edit anything outside the markers freely.

${AGENT_BLOCK_START}
${block}
${AGENT_BLOCK_END}
`;
};

// Claude Code natively imports other files with \`@path\`, so CLAUDE.md stays a thin pointer to AGENTS.md
// instead of duplicating its content.
const renderClaudeMd = async (workspace: Workspace) => {
  const context = await AkanContextAnalyzer.analyze(workspace);
  return `# ${context.repoName} — Claude Code Guide

@AGENTS.md
`;
};

// Cursor rules reference AGENTS.md rather than carrying their own copy.
const renderCursorRule = () => `---
description: Akan workspace agent guide
alwaysApply: true
---

Follow the workspace agent guide, which is the single source of truth for Akan conventions,
generated-file rules, and the MCP workflow policy.

@AGENTS.md
`;

const renderTarget = async (workspace: Workspace, target: AgentTarget, existing: string | null) => {
  if (target === "agents-md") return await renderAgentsMd(workspace, existing);
  if (target === "claude") return await renderClaudeMd(workspace);
  return renderCursorRule();
};

export class AgentRunner extends runner("agent") {
  async install(workspace: Workspace, targets: AgentTarget[], { force = false }: { force?: boolean } = {}) {
    const written: string[] = [];
    for (const target of targets) {
      const filePath = targetPaths[target];
      const exists = await workspace.exists(filePath);
      // AGENTS.md updates only the managed block, so refreshing an existing file is safe without --force.
      // CLAUDE.md and the Cursor rule are canonical pointers, so overwriting them needs --force.
      if (exists && !force && target !== "agents-md") {
        throw new Error(`${filePath} already exists. Re-run with --force to overwrite it.`);
      }
      const existing = exists ? await workspace.readFile(filePath) : null;
      const content = await renderTarget(workspace, target, existing);
      await workspace.writeFile(filePath, content, { overwrite: true });
      written.push(filePath);
    }
    return written;
  }
}
