import { AkanContextAnalyzer, Prompter, runner, type Workspace } from "@akanjs/devkit";

type AgentTarget = "cursor" | "agents-md" | "claude";

const targetPaths: Record<AgentTarget, string> = {
  cursor: ".cursor/rules/akan.mdc",
  "agents-md": "AGENTS.md",
  claude: "CLAUDE.md",
};

const targetTitle: Record<AgentTarget, string> = {
  cursor: "Akan Cursor Rules",
  "agents-md": "Akan Agent Rules",
  claude: "Akan Claude Rules",
};

const renderAgentRules = async (workspace: Workspace, target: AgentTarget) => {
  const context = await AkanContextAnalyzer.analyze(workspace);
  const frameworkGuide = await Prompter.getInstruction("framework");
  return `# ${targetTitle[target]}

This file is generated by \`akan agent install ${target}\`.

## Workspace

- Repo: ${context.repoName}
- Apps: ${context.apps.map((app) => app.name).join(", ") || "none"}
- Libraries: ${context.libs.map((lib) => lib.name).join(", ") || "none"}
- Packages: ${context.pkgs.map((pkg) => pkg.name).join(", ") || "none"}

## Akan Module Abstracts

- Before changing a domain, service, or scalar module, read its \`*.abstract.md\` file first.
- Update the abstract when business invariants, workflows, or public behavior change.
- Do not update the abstract for formatting-only, import-only, or style-only changes.
- Service modules live in \`lib/_<service>\`, but their abstract file is \`<service>.abstract.md\`.

## Generated Files

Do not hand-edit generated registry files such as ${context.generatedFiles.map((file) => `\`${file}\``).join(", ")}.

## Validation

${context.validationCommands.map((command) => `- \`${command}\``).join("\n")}

## Framework Guide

${frameworkGuide.trim()}
`;
};

export class AgentRunner extends runner("agent") {
  async install(workspace: Workspace, targets: AgentTarget[], { force = false }: { force?: boolean } = {}) {
    const written: string[] = [];
    for (const target of targets) {
      const filePath = targetPaths[target];
      if (!force && (await workspace.exists(filePath))) {
        throw new Error(`${filePath} already exists. Re-run with --force to overwrite it.`);
      }
      const content = await renderAgentRules(workspace, target);
      await workspace.writeFile(filePath, content, { overwrite: force });
      written.push(filePath);
    }
    return written;
  }
}
