import { usePage } from "@apps/akan/client";
import { Code, Divider, Docs, DocsList, DocsToc } from "@apps/akan/ui";
import { Scroll } from "@libs/util/ui";

export default function Page() {
  const { l } = usePage();

  return (
    <Scroll>
      <Scroll.Slide id="overview" title={l.trans({ en: "Server Console", ko: "Server Console" })}>
        <Docs.Title>{l.trans({ en: "Server Console", ko: "Server Console" })}</Docs.Title>
        <Docs.Description>
          <div>
            {l.trans({
              en: "Use the Akan server console for interactive inspection and small operator commands against an initialized app runtime.",
              ko: "Akan server console은 초기화된 app runtime을 대상으로 interactive 점검과 작은 운영 명령을 실행할 때 사용합니다.",
            })}
          </div>
          <DocsList>
            <li>
              {l.trans({
                en: "`akan console` is the local development entry.",
                ko: "`akan console`은 local development용 entry입니다.",
              })}
            </li>
            <li>
              {l.trans({
                en: "`console.js` is generated by `akan build` and is embedded next to `main.js` in the production dist files.",
                ko: "`console.js`는 `akan build`가 생성하며 production dist 안에서 `main.js` 옆에 포함됩니다.",
              })}
            </li>
            <li>
              {l.trans({
                en: "Do not create console files manually inside a running container or pod.",
                ko: "실행 중인 container나 pod 안에서 console 파일을 직접 만들지 마세요.",
              })}
            </li>
          </DocsList>
        </Docs.Description>
      </Scroll.Slide>
      <Divider />

      <Scroll.Slide id="local" title={l.trans({ en: "Local Console", ko: "Local console" })}>
        <Docs.Title>{l.trans({ en: "Local Console", ko: "Local console" })}</Docs.Title>
        <Docs.Description>
          <div>
            {l.trans({
              en: "Open a local console when you want to inspect services, call small methods, or try a quick query without writing a repeatable script file.",
              ko: "반복 가능한 script 파일을 만들지 않고 service를 점검하거나 작은 method, query를 실행하고 싶을 때 local console을 엽니다.",
            })}
          </div>
        </Docs.Description>
        <Code.Snippet
          className="w-full"
          title={l.trans({ en: "Run locally", ko: "Local 실행" })}
          language="bash"
          code="akan console myapp"
        />
      </Scroll.Slide>
      <Divider />

      <Scroll.Slide id="multiline" title={l.trans({ en: "Multi-line Input", ko: "여러 줄 입력" })}>
        <Docs.Title>{l.trans({ en: "Multi-line Input", ko: "여러 줄 입력" })}</Docs.Title>
        <Docs.Description>
          <div>
            {l.trans({
              en: "Paste a snippet as it is: the console reads a pasted block as one command instead of running it line by line.",
              ko: "코드를 그대로 붙여넣으면 됩니다. Console은 붙여넣은 block을 한 줄씩 실행하지 않고 하나의 command로 읽습니다.",
            })}
          </div>
          <DocsList>
            <li>
              {l.trans({
                en: "A `const` declared on the first pasted line is visible on the last one.",
                ko: "붙여넣은 첫 줄에서 선언한 `const`를 마지막 줄에서 사용할 수 있습니다.",
              })}
            </li>
            <li>
              {l.trans({
                en: "A line that ends inside an open bracket, string, or comment keeps reading at the `...` prompt.",
                ko: "괄호나 문자열, comment가 닫히지 않은 줄은 `...` prompt에서 계속 입력을 받습니다.",
              })}
            </li>
            <li>
              {l.trans({
                en: "`const` and `let` live for one command only, so assign without a keyword to keep a value.",
                ko: "`const`와 `let`은 한 command 안에서만 유지되므로, 값을 남기려면 keyword 없이 대입하세요.",
              })}
            </li>
            <li>
              {l.trans({
                en: "End a block with `return <expr>` to print its value.",
                ko: "Block의 값을 출력하려면 `return <expr>`로 끝내세요.",
              })}
            </li>
            <li>
              {l.trans({
                en: "`.clear` or Ctrl+C discards the pending input, and Ctrl+D closes the console.",
                ko: "`.clear`나 Ctrl+C는 입력 중인 내용을 버리고, Ctrl+D는 console을 닫습니다.",
              })}
            </li>
          </DocsList>
        </Docs.Description>
        <Code.Snippet
          className="w-full"
          title={l.trans({ en: "One pasted command", ko: "붙여넣은 하나의 command" })}
          code={`const user = await service("user").pickById("6890f2c1f0a1b2c3d4e5f6a7");
user.name = "changed";
return await user.save();`}
        />
      </Scroll.Slide>
      <Divider />

      <Scroll.Slide id="container" title={l.trans({ en: "Container Console", ko: "Container console" })}>
        <Docs.Title>{l.trans({ en: "Container Console", ko: "Container console" })}</Docs.Title>
        <Docs.Description>
          <div>
            {l.trans({
              en: "In Docker or Kubernetes, execute the generated `console.js` that already exists in the built image.",
              ko: "Docker나 Kubernetes에서는 build image 안에 이미 들어 있는 generated `console.js`를 실행합니다.",
            })}
          </div>
          <div>
            {l.trans({
              en: "Set `AKAN_CONSOLE=1` on the exec command itself for production-like environments. Avoid keeping it permanently in deployment env.",
              ko: "production 계열 환경에서는 exec 명령 자체에만 `AKAN_CONSOLE=1`을 설정하세요. Deployment env에 영구적으로 넣지 않는 것이 좋습니다.",
            })}
          </div>
        </Docs.Description>
        <Code.Snippet
          className="w-full"
          title={l.trans({ en: "Docker", ko: "Docker" })}
          language="bash"
          code="docker exec -it myapp sh -lc 'AKAN_CONSOLE=1 bun console.js'"
        />
        <Code.Snippet
          className="w-full"
          title={l.trans({ en: "Kubernetes", ko: "Kubernetes" })}
          language="bash"
          code="kubectl exec -it -n prod pod/myapp-xxxxx -c myapp -- sh -lc 'AKAN_CONSOLE=1 bun console.js'"
        />
      </Scroll.Slide>
      <Divider />

      <Scroll.Slide id="lifecycle" title={l.trans({ en: "Lifecycle", ko: "Lifecycle" })}>
        <Docs.Title>{l.trans({ en: "Lifecycle", ko: "Lifecycle" })}</Docs.Title>
        <Docs.Description>
          <DocsList>
            <li>
              {l.trans({
                en: "Container console mode starts a separate no-listen server process inside the same container or pod.",
                ko: "Container console mode는 같은 container나 pod 안에서 별도의 no-listen server process를 시작합니다.",
              })}
            </li>
            <li>
              {l.trans({
                en: "It shares env, secrets, mounted volumes, network, and database access with the running app container.",
                ko: "실행 중인 app container와 env, secret, mounted volume, network, database access를 공유합니다.",
              })}
            </li>
            <li>
              {l.trans({
                en: "It does not attach to the already-running `main.js` process or its in-memory state.",
                ko: "이미 실행 중인 `main.js` process나 그 in-memory state에 attach하지는 않습니다.",
              })}
            </li>
            <li>
              {l.trans({
                en: "Console mode must keep scheduler and cron work disabled because it is a second process.",
                ko: "Console mode는 두 번째 process이므로 scheduler와 cron 작업이 실행되지 않게 유지해야 합니다.",
              })}
            </li>
          </DocsList>
        </Docs.Description>
      </Scroll.Slide>
      <Divider />

      <Scroll.Slide id="globals" title={l.trans({ en: "Globals", ko: "Globals" })}>
        <Docs.Title>{l.trans({ en: "Globals", ko: "Globals" })}</Docs.Title>
        <Docs.Description>
          <div>
            {l.trans({
              en: "The console exposes runtime helpers and generated app exports so small commands stay short.",
              ko: "Console은 작은 명령을 짧게 유지할 수 있도록 runtime helper와 generated app export를 제공합니다.",
            })}
          </div>
          <DocsList>
            <li>
              {l.trans({
                en: "`server`, `env`: current server instance and environment.",
                ko: "`server`, `env`: 현재 server instance와 environment.",
              })}
            </li>
            <li>
              {l.trans({
                en: "`get`, `service`, `signal`, `adaptor`: lookup helpers for runtime objects.",
                ko: "`get`, `service`, `signal`, `adaptor`: runtime object lookup helper입니다.",
              })}
            </li>
            <li>
              {l.trans({
                en: "`methods`, `debug`: inspect public methods and runtime registration state.",
                ko: "`methods`, `debug`: public method와 runtime registration state를 점검합니다.",
              })}
            </li>
            <li>
              {l.trans({
                en: "`srv`, `sig`, `db`, `cnst`: generated app exports.",
                ko: "`srv`, `sig`, `db`, `cnst`: generated app export입니다.",
              })}
            </li>
          </DocsList>
        </Docs.Description>
        <Code.Snippet
          className="w-full"
          title={l.trans({ en: "Examples", ko: "예시" })}
          code={`process.env.AKAN_PUBLIC_ENV
env
debug()
methods(service("user"))
await service("user").__count()
await get(srv.UserService).__count()`}
        />
      </Scroll.Slide>
      <Divider />

      <Scroll.Slide id="safety" title={l.trans({ en: "Safety", ko: "Safety" })}>
        <Docs.Title>{l.trans({ en: "Safety", ko: "Safety" })}</Docs.Title>
        <Docs.Description>
          <DocsList>
            <li>
              {l.trans({
                en: "Print and check the target environment before changing data.",
                ko: "데이터를 변경하기 전에 대상 environment를 출력하고 확인하세요.",
              })}
            </li>
            <li>
              {l.trans({
                en: "Prefer service methods over direct database writes so domain rules still run.",
                ko: "Domain rule이 계속 실행되도록 직접 database를 쓰기보다 service method를 우선 사용하세요.",
              })}
            </li>
            <li>
              {l.trans({
                en: "For destructive work, write a script with dry-run or confirmation instead of typing many console commands by hand.",
                ko: "파괴적인 작업은 console에 여러 명령을 직접 치기보다 dry-run이나 confirm이 있는 script로 작성하세요.",
              })}
            </li>
            <li>
              {l.trans({
                en: "Keep `AKAN_CONSOLE=1` out of permanent deployment configuration.",
                ko: "`AKAN_CONSOLE=1`은 영구 deployment configuration에 넣지 마세요.",
              })}
            </li>
          </DocsList>
        </Docs.Description>
      </Scroll.Slide>
      <DocsToc />
    </Scroll>
  );
}
