export const stays = {
  skyline: {
    title: "Skyline Loft",
    area: "Seolleung · Seoul",
    summary: "City night views from the 27th floor, with a quiet lounge for late check-ins.",
    image: "/stays/skyline.webp",
    nightly: 168000,
    rating: "4.92",
    guests: 2,
    bedrooms: 1,
    view: "27F",
  },
  river: {
    title: "River View Suite",
    area: "Yeouido · Seoul",
    summary: "Wake up to the Han River and walk to the night market along the water.",
    image: "/stays/river.webp",
    nightly: 128000,
    rating: "4.88",
    guests: 2,
    bedrooms: 1,
    view: "River",
  },
  lounge: {
    title: "Quiet Work Lounge",
    area: "Seongsu · Seoul",
    summary: "A desk by the window, fast Wi-Fi and a café downstairs, built for focused work.",
    image: "/stays/lounge.webp",
    nightly: 74000,
    rating: "4.81",
    guests: 1,
    bedrooms: 1,
    view: "Park",
  },
  terrace: {
    title: "Garden House",
    area: "Yeonnam · Seoul",
    summary: "A sunny terrace for brunch and a small garden that stays green all year.",
    image: "/stays/terrace.webp",
    nightly: 92000,
    rating: "4.95",
    guests: 4,
    bedrooms: 2,
    view: "Garden",
  },
} as const;
