import { pushNavigateMessage } from "../common/pushNavigateMessage";

const FIREBASE_WEB_SDK_VERSION = "12.13.0";

//* 이 배너로 시작하는 파일만 재생성 대상이다. 앱이 워커를 직접 소유하고 싶으면 배너를 지우면 된다.
export const generatedServiceWorkerBanner =
  "/* Generated by Akan.js. Do not edit — remove this line to own this file. */";

export interface FirebaseClientEnvConfig {
  apiKey: string;
  authDomain?: string;
  projectId: string;
  storageBucket?: string;
  messagingSenderId: string;
  appId: string;
  vapidKey?: string;
}

//* env.client 의 firebase 설정을 검증하고, 서비스워커에 필요한 필드만 화이트리스트한다.
//* vapidKey/서버 시크릿 등 나머지 필드는 의도적으로 제외한다(SW 본문에 유출 방지).
export function normalizeFirebaseClientConfig(config: unknown): FirebaseClientEnvConfig | null {
  if (!config || typeof config !== "object") return null;
  const value = config as Partial<Record<keyof FirebaseClientEnvConfig, unknown>>;
  if (
    typeof value.apiKey !== "string" ||
    typeof value.projectId !== "string" ||
    typeof value.messagingSenderId !== "string" ||
    typeof value.appId !== "string"
  ) {
    return null;
  }
  return {
    apiKey: value.apiKey,
    ...(typeof value.authDomain === "string" ? { authDomain: value.authDomain } : {}),
    projectId: value.projectId,
    ...(typeof value.storageBucket === "string" ? { storageBucket: value.storageBucket } : {}),
    messagingSenderId: value.messagingSenderId,
    appId: value.appId,
  };
}

//* firebase-messaging-sw.js 생성 코드
export function createFirebaseMessagingServiceWorker(config: FirebaseClientEnvConfig | null): string {
  const configJson = JSON.stringify(config);
  return `${generatedServiceWorkerBanner}
const firebaseConfig = ${configJson};

// The body is regenerated whenever the framework or the client env changes, so an already-installed worker
// would otherwise only activate on the visit after next.
self.addEventListener("install", () => self.skipWaiting());
self.addEventListener("activate", (event) => event.waitUntil(self.clients.claim()));

const applyBadge = (count) => {
  // Firefox and desktop Safari ship no setAppBadge; calling it unguarded is a synchronous TypeError.
  if (typeof count === "undefined" || !navigator.setAppBadge) return;
  const parsed = Number.parseInt(count, 10);
  if (Number.isNaN(parsed)) return;
  void navigator.setAppBadge(parsed);
};

const notificationUrl = (payload) =>
  payload?.data?.url || payload?.fcmOptions?.link || payload?.notification?.click_action;

const openDeepLink = async (url) => {
  const target = new URL(url, self.location.origin);
  const windows = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
  const existing = windows.find((client) => new URL(client.url).origin === target.origin);
  if (!existing) {
    await self.clients.openWindow(target.href);
    return;
  }
  // Reusing the open tab keeps this a client-side route change instead of a full reload of the whole app.
  await existing.focus();
  existing.postMessage({
    type: "${pushNavigateMessage}",
    url: \`\${target.pathname}\${target.search}\${target.hash}\`,
  });
};

if (firebaseConfig) {
  importScripts("https://www.gstatic.com/firebasejs/${FIREBASE_WEB_SDK_VERSION}/firebase-app-compat.js");
  importScripts("https://www.gstatic.com/firebasejs/${FIREBASE_WEB_SDK_VERSION}/firebase-messaging-compat.js");

  firebase.initializeApp(firebaseConfig);
  const messaging = firebase.messaging();

  messaging.onBackgroundMessage((payload) => {
    applyBadge(payload?.data?.badgeCount);
    // firebase-js-sdk's sw-controller draws a payload carrying a \`notification\` block itself and only then
    // calls this handler, so drawing it again here is what turns one push into two notifications.
    if (payload?.notification) return;
    const data = payload?.data ?? {};
    if (!data.title && !data.body) return;
    self.registration.showNotification(data.title || "", {
      body: data.body,
      icon: data.icon,
      image: data.image,
      tag: data.tag,
      // renotify without a tag throws; together they re-alert an update that replaced its predecessor.
      renotify: !!data.tag,
      data: { url: notificationUrl(payload), FCM_MSG: payload },
    });
  });
}

self.addEventListener("notificationclick", (event) => {
  const url = event.notification?.data?.url || event.notification?.data?.FCM_MSG?.data?.url;
  event.notification?.close();
  if (!url) return;
  event.waitUntil(openDeepLink(url));
});
`;
}
